// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node prisma/seed.ts",
  },
  datasource: {
    // Prisma CLI (migrate, db push, studio) should always use a direct, unpooled
    // connection. In production this is Neon's direct URL; locally it's the same
    // as DATABASE_URL. Fall back to DATABASE_URL when DIRECT_URL isn't set.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
