-- AlterEnum
ALTER TYPE "Intent" ADD VALUE 'NOT_PROCESSED';

-- AlterTable
ALTER TABLE "AgentDecision" ALTER COLUMN "confidence" DROP NOT NULL,
ALTER COLUMN "tier" DROP NOT NULL,
ALTER COLUMN "reasoning" DROP NOT NULL,
ALTER COLUMN "llmModel" DROP NOT NULL,
ALTER COLUMN "tokensIn" DROP NOT NULL,
ALTER COLUMN "tokensOut" DROP NOT NULL,
ALTER COLUMN "latencyMs" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Parent" ADD COLUMN     "isVerified" BOOLEAN NOT NULL DEFAULT false;
